version: '3.0'
services:
  java-stress-rdb-apm:
    image: 'stressjava-rdb-apm-new:latest'
    build:
      context: ./
      args:
        REVDEBUG_COMPILER_VERSION_ARG: ${REVDEBUG_COMPILER_VERSION:-6.1.16-SNAPSHOT-1635951658}
        REVDEBUG_HOST_ARG: ${REVDEBUG_HOST:-20.199.127.147}
        REVDEBUG_FORCE_TLS_ARG: ${REVDEBUG_FORCE_TLS:-false}
        REVDEBUG_OFF_ARG: ${REVDEBUG_OFF:-false}
        SW_AGENT_VERSION: ${SW_AGENT_VERSION:-6.1.16}
        SW_AGENT_ACTIVE_ARG: ${SW_AGENT_ACTIVE:-1}
        SW_AGENT_FORCE_TLS_ARG: ${SW_AGENT_FORCE_TLS:-false}
        SW_AGENT_COLLECTOR_BACKEND_SERVICES_ARG: ${SW_AGENT_COLLECTOR_BACKEND_SERVICES:-20.199.127.147:11800}
    ports:
      - '8000:8080'
  java-stress-rdb:
    image: 'stressjava-rdb-new:latest'
    build:
      context: ./
      args:
        REVDEBUG_COMPILER_VERSION_ARG: ${REVDEBUG_COMPILER_VERSION:-6.1.16-SNAPSHOT-1635951658}
        REVDEBUG_HOST_ARG: ${REVDEBUG_HOST:-20.199.127.147}
        REVDEBUG_FORCE_TLS_ARG: ${REVDEBUG_FORCE_TLS:-false}
        REVDEBUG_OFF_ARG: ${REVDEBUG_OFF:-false}
        SW_AGENT_VERSION: ${SW_AGENT_VERSION:-6.1.16}
        SW_AGENT_ACTIVE_ARG: ${SW_AGENT_ACTIVE:-0}
        SW_AGENT_FORCE_TLS_ARG: ${SW_AGENT_FORCE_TLS:-false}
        SW_AGENT_COLLECTOR_BACKEND_SERVICES_ARG: ${SW_AGENT_COLLECTOR_BACKEND_SERVICES:-20.199.127.147:11800}
    ports:
      - '8001:8080'
  java-stress-apm:
    image: 'stressjava-apm-new:latest'
    build:
      context: ./
      args:
        REVDEBUG_COMPILER_VERSION_ARG: ${REVDEBUG_COMPILER_VERSION:-6.1.16-SNAPSHOT-1635951658}
        REVDEBUG_HOST_ARG: ${REVDEBUG_HOST:-20.199.127.147}
        REVDEBUG_FORCE_TLS_ARG: ${REVDEBUG_FORCE_TLS:-false}
        REVDEBUG_OFF_ARG: ${REVDEBUG_OFF:-true}
        SW_AGENT_VERSION: ${SW_AGENT_VERSION:-6.1.16}
        SW_AGENT_ACTIVE_ARG: ${SW_AGENT_ACTIVE:-1}
        SW_AGENT_FORCE_TLS_ARG: ${SW_AGENT_FORCE_TLS:-false}
        SW_AGENT_COLLECTOR_BACKEND_SERVICES_ARG: ${SW_AGENT_COLLECTOR_BACKEND_SERVICES:-20.199.127.147:11800}
    ports:
      - '8002:8080'
  java-stress-none:
    image: 'stressjava-none-new:latest'
    build:
      context: ./
      dockerfile: dockerfile.none
    ports:
      - '8003:8080'