#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build

RUN apt-get update
RUN apt-get install -y wget
COPY src /home/app/src
COPY pom_none.xml /home/app/pom.xml
COPY .git /home/app/.git


RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM openjdk:11-jre-slim

COPY --from=build /home/app/target/demo-0.0.1-SNAPSHOT.jar /usr/local/lib/demo.jar
CMD java -jar /usr/local/lib/demo.jar